export const data = JSON.parse("{\"key\":\"v-22e38636\",\"path\":\"/zh/guide/introduction/introduction.html\",\"title\":\"关于openGemini\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"openGemini简介 openGemini是华为云数据库创新Lab (https://www.huaweicloud.com/lab/clouddb/home.html)自主设计、研发的一款面向全球开源的云原生分布式时序数据库，提供单机和分布式版本，具备卓越的读写性能和高效的数据分析能力，支持主流开发语言和多形态部署（如云、Docker、物理机等）...\",\"head\":[[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://shilinlee.github.io/docs/docs/guide/introduction/introduction.html\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://shilinlee.github.io/docs/docs/zh/guide/introduction/introduction.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"openGemini\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"关于openGemini\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"openGemini简介 openGemini是华为云数据库创新Lab (https://www.huaweicloud.com/lab/clouddb/home.html)自主设计、研发的一款面向全球开源的云原生分布式时序数据库，提供单机和分布式版本，具备卓越的读写性能和高效的数据分析能力，支持主流开发语言和多形态部署（如云、Docker、物理机等）...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.openGemini\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"关于openGemini\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.openGemini\\\",\\\"url\\\":\\\"https://openGemini.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"openGemini简介\",\"slug\":\"opengemini简介\",\"link\":\"#opengemini简介\",\"children\":[]},{\"level\":2,\"title\":\"五大核心特性\",\"slug\":\"五大核心特性\",\"link\":\"#五大核心特性\",\"children\":[{\"level\":3,\"title\":\"高性能\",\"slug\":\"高性能\",\"link\":\"#高性能\",\"children\":[]},{\"level\":3,\"title\":\"分布式\",\"slug\":\"分布式\",\"link\":\"#分布式\",\"children\":[]},{\"level\":3,\"title\":\"存储分析一体化\",\"slug\":\"存储分析一体化\",\"link\":\"#存储分析一体化\",\"children\":[]},{\"level\":3,\"title\":\"运维成本低\",\"slug\":\"运维成本低\",\"link\":\"#运维成本低\",\"children\":[]},{\"level\":3,\"title\":\"高数据压缩率\",\"slug\":\"高数据压缩率\",\"link\":\"#高数据压缩率\",\"children\":[]}]},{\"level\":2,\"title\":\"典型应用场景\",\"slug\":\"典型应用场景\",\"link\":\"#典型应用场景\",\"children\":[{\"level\":3,\"title\":\"物联网（IoT）\",\"slug\":\"物联网-iot\",\"link\":\"#物联网-iot\",\"children\":[]},{\"level\":3,\"title\":\"监控（DevOps）\",\"slug\":\"监控-devops\",\"link\":\"#监控-devops\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.17,\"words\":952},\"filePathRelative\":\"zh/guide/introduction/introduction.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
